wandb_version: 1

is_training:
  desc: null
  value: 1
model_id:
  desc: null
  value: EES
model:
  desc: null
  value: OSLSTMv2
data:
  desc: null
  value: Batteries_cycle_SLMove
root_path:
  desc: null
  value: ./dataset/HUST_cycle_data/
data_path:
  desc: null
  value: ''
features:
  desc: null
  value: M
target:
  desc: null
  value: OT
freq:
  desc: null
  value: h
checkpoints:
  desc: null
  value: ./checkpoints/
scale:
  desc: null
  value: true
seq_len:
  desc: null
  value: 90
label_len:
  desc: null
  value: 90
pred_len:
  desc: null
  value: 950
bucket_size:
  desc: null
  value: 48
n_hashes:
  desc: null
  value: 4
enc_in:
  desc: null
  value: 2
dec_in:
  desc: null
  value: 2
c_out:
  desc: null
  value: 2
d_model:
  desc: null
  value: 12
n_heads:
  desc: null
  value: 4
e_layers:
  desc: null
  value: 2
d_layers:
  desc: null
  value: 1
d_ff:
  desc: null
  value: 4
moving_avg:
  desc: null
  value: 15
factor:
  desc: null
  value: 5
factor2:
  desc: null
  value: 1
distil:
  desc: null
  value: false
dropout:
  desc: null
  value: 0.0
embed:
  desc: null
  value: Cycle
activation:
  desc: null
  value: gelu
output_attention:
  desc: null
  value: false
do_predict:
  desc: null
  value: false
FT:
  desc: null
  value: false
val_ratio:
  desc: null
  value: 0.5
iterations:
  desc: null
  value: 10000
test_every:
  desc: null
  value: 500
num_workers:
  desc: null
  value: 8
wd:
  desc: null
  value: 0
itr:
  desc: null
  value: 1
train_epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 128
patience:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.0075
meta_learning_rate:
  desc: null
  value: 0.0075
meta_beta:
  desc: null
  value: 2
auxiliary_gamma:
  desc: null
  value: 0.2
meta_train:
  desc: null
  value: false
lr_align:
  desc: null
  value: false
des:
  desc: null
  value: test
loss:
  desc: null
  value: mse
vali_loss:
  desc: null
  value: nw
gamma1:
  desc: null
  value: 0.0
gamma2:
  desc: null
  value: 0.0
lradj:
  desc: null
  value: type4
use_amp:
  desc: null
  value: false
use_gpu:
  desc: null
  value: true
gpu:
  desc: null
  value: 5
use_multi_gpu:
  desc: null
  value: false
devices:
  desc: null
  value: 4,5,6,7
nominal_capacity:
  desc: null
  value: 1.1
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722067352.478263
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
